### ISSUE TITLE
The search term "(Pantun" returns a blank page

### ISSUE THREAD

**Issue by irfanzainudin** [irfanzainudin/pantunis#1]
Not sure if this should be considered an issue because I don't think the term "(Pantun" should even be in the database. The term "(Pantun" exists in the database now because I want to keep track which pantun is part of a collection. For example, the collection of Pantun Sarawak. If you search for "pantun sarawak", the API will return pantuns that are part of the collection.

For future improvements, we can implement search by tags and the collection names will be the tag names.

With that being said, I do believe this is a bug. I haven't tested for any other punctuations except the comma (,). The comma works well.

If anyone find other punctuations that error, please reply to this issue, thanks!

**Comment by irsyadpage** [comment]
The `(` is part of special characters for regular expressions. Therefore, it must be escape using backslash before adding to the `RegExp` function.

See #2 for solution.

**Comment by irfanzainudin** [comment]
Yup, looked it over and everything looks great, merged!
